alias newlinestring='sed -e '\'':a'\'' -e '\''N'\'' -e '\''$!ba'\'' -e '\''s/\n/\\n/g'\'
alias newlinecomma='sed -e '\'':a'\'' -e '\''N'\'' -e '\''$!ba'\'' -e '\''s/\n/,/g'\'
alias newlinespace='sed -e '\'':a'\'' -e '\''N'\'' -e '\''$!ba'\'' -e '\''s/\n/\ /g'\'

alias ls='/bin/ls -F --color=auto'
alias lc='/bin/ls -F --color'
alias grep='/usr/bin/grep --color=auto'
alias egrep='/usr/bin/egrep --color=auto'
alias tree='tree -C'
alias s='source ~/git/scripts/sshfzf.sh'
alias r='source ~/bin/cdroot.sh'
alias f='source ~/bin/fzfcd.sh'
alias fs='~/bin/fzfsecrets.sh'
alias c='~/git/core-tools/bin/clogin'
alias k='~/bin/kitchenlogin.sh'
alias kc='~/bin/kitchenconv.sh'
alias v='/usr/bin/nvim'
alias b='cd ~/notes'
alias q='~/git/scripts/qkill.sh'
alias vim=nvim
alias rm='rm -i'
alias pssh='pssh -t 0'
alias h='cp ~/.config/hypr/conf/monitor.conf.laptop ~/.config/hypr/conf/monitor.conf;Hyprland'
alias n='~/bin/nirisession.sh'
